### ISSUE TITLE
Removing older IPs from NEXUS_CLUS_URL in nexus conf

### ISSUE THREAD

**Issue by nitin4123003** [flipkart-incubator/nexus#5]
Currently we have to keep all the previous member IPs as well as a part of the NEXUS_CLUS_URL in nexus conf. The older IPs might not exist any more due to migration/VM destroyed/any other reason. But still we have to keep on carrying them throughout the cluster lifecycle.If we try to remove them and start nexus then nexus gives an ARRAY OUT OF BOUNDS Exception as node id is directly used an array index in the nexus code.

Can we change this so that we don't have to carry non existent IPs throughout the cluster lifecycle?

**Comment by KalyanAkella** [comment]
Commits [this](https://github.com/flipkart-incubator/nexus/commit/1364a10481133a4c25fe1b0c9659f1560c96af46) and [this](https://github.com/flipkart-incubator/nexus/commit/c900733e05ea33abac762fcd162ddad1788a2f4c) no longer depend on node index in the cluster array. Please reopen this if you're seeing any further array index bounds errors.
